apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gateway-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gateway-chart.name" . }}
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"

            - name: SERVICE_URL
              value: "http://dev.adenali.com"

          envFrom:
            - secretRef:
                name: gateway-secrets
