apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gateway-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gateway-chart.name" . }}
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}

            {{- if .Values.envFromSecret }}
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envFromSecret }}
                  key: JWT_SECRET_KEY
            {{- end }}
