replicaCount: 1

image:
  repository: adenli/gateway-service
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: LoadBalancer
  port: 8080

env:
  SPRING_PROFILES_ACTIVE: dev

envFromSecret: ""
